// Code generated by Thrift Compiler (0.14.0). DO NOT EDIT.

package sharestore

import(
	"bytes"
	"context"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

const DEFAULT_MAX_NUMS = 5000

func init() {
}

